#!/bin/bash
for folder in ./*/;
do
    cd "$folder"  || exit 
	if git pull 2>/dev/null | grep -qv 'Already'; then
   		echo "${folder%%/} : MUST be updated"
		makepkg -rsci
	else
   		echo "OK: ${folder%%/}"
	fi
    cd ..
done
