#!/bin/bash

source colors
color=$grey

INFO=$(acpi|grep -v "unavailable")

STATE=$(echo "$INFO" | grep -o "Charging")
LEVEL_PRCNTS=$(echo "$INFO"| grep -o '[0-9]\+%')
LEVEL=${LEVEL_PRCNTS:: -1}

if [[ "$LEVEL" -gt 80 ]];
	then 
		ICON=""  
elif [[ "$LEVEL" -gt 60 &&  "$LEVEL" -lt 81 ]];
	then 
		ICON=""  
		#color=$white
elif [[ "$LEVEL" -gt 40 &&  "$LEVEL" -lt 61 ]]; 
	then 
		ICON=""
		color=$white
elif [[ "$LEVEL" -gt 20 &&  "$LEVEL" -lt 41 ]]; 
	then 
		ICON=""
		color=$white
elif [[ "$LEVEL" -lt 21 ]];
	then 
		ICON=""
		color=$red
fi

if [[ "$(echo "$INFO" | grep -o "Charging")" ]]; 
	then 
		color=$green; 
fi

if [[ "$BLOCK_BUTTON" == 1 ]]; 
	then 
		TEXT="<span color='$color'>$ICON $LEVEL_PRCNTS</span>";
	else
		TEXT="<span color='$color'>$ICON</span>"; 
fi

echo $TEXT
