#!/bin/bash

INFO=$(acpi|grep -v "unavailable")

STATE=$(echo "$INFO" | grep -o "Charging")
LEVEL_PRCNTS=$(echo "$INFO"| grep -o '[0-9]\+%')
LEVEL=${LEVEL_PRCNTS:: -1}

MAIN_COLOR="#a89984"
ICON_COLOR=$MAIN_COLOR

if   [[ "$LEVEL" -gt 80 ]]; 					then ICON=""  
elif [[ "$LEVEL" -gt 60 &&  "$LEVEL" -lt 81 ]]; then ICON=""  
elif [[ "$LEVEL" -gt 40 &&  "$LEVEL" -lt 61 ]]; then ICON=""  
elif [[ "$LEVEL" -gt 20 &&  "$LEVEL" -lt 41 ]]; then ICON=""  
elif [[ "$LEVEL" -lt 21 ]]; 					then ICON=""  ICON_COLOR="red"
fi

if [[ "$(echo "$INFO" | grep -o "Charging")" ]]; then ICON_COLOR="green"; fi

if [[ "$BLOCK_BUTTON" == 1 ]]; then TEXT="<span color='$MAIN_COLOR'>$LEVEL_PRCNTS</span>"; fi

echo "<span color='$ICON_COLOR'>$ICON</span>"$TEXT
