#!/bin/bash

source colors
color=$grey
icon=

lang=$(xkb-switch|sed -r 's/\(.+//g')

if [[ "$(xset -q | grep Caps | awk '{ print $4 }')" =~ "on" ]]
	then 
		lang=${lang^^}
fi

if [[ "$BLOCK_BUTTON" == 1 ]]; 
then 
	xkb-switch -n
fi


TEXT="<span color='$color'>$lang</span>"
echo $TEXT
