#!/bin/bash

source colors
color=$grey
#icon=

weather_long=$(curl -s curl -s wttr.in/?format="%l:+%C+%t/%f+%w+%p+%P=%m\n")
weather_short=$(curl -s wttr.in/?format="+%C+%f+%w+%p\n")

if [[ "$BLOCK_BUTTON" == 1 ]]; 
	then 
		TEXT="$icon $weather_long"
	else
		TEXT="$icon $weather_short"
fi

echo $TEXT
