#!/bin/bash

source colors
color=$grey
ICON= 

if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi

[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit


QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
SSID=$(iw dev $INTERFACE link|grep SSID:|awk '{print $2}')
IP=$(curl -Ss ifconfig.me/all|grep ip_addr|awk '{print $2}')


# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    color=$red
    echo "down"
    exit
elif [[ $QUALITY -lt 60 ]]; then
    color=$yellow
elif [[ $QUALITY -lt 40 ]]; then
    color=$orange
fi


if [[ "$BLOCK_BUTTON" == 1 ]]; 
	then TEXT="<span color='$color'>$ICON $QUALITY% $IP@$SSID  </span>"; 
else
	TEXT="<span color=\"${color}\">$ICON</span>"
fi

echo $TEXT
